# Generated by Django 3.1 on 2021-04-25 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="b",
        ),
        migrations.AlterField(
            model_name="media",
            name="creation_date",
            field=models.DateField(blank=True, default=None, verbose_name="дата создания фильма"),
        ),
    ]
