# Generated by Django 3.1 on 2021-04-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20210425_2359"),
    ]
    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name": "кинопроизведение", "verbose_name_plural": "кинопроизведения"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "перносж", "verbose_name_plural": "персонаж"},
        ),
        migrations.AlterModelOptions(
            name="personmedia",
            options={"verbose_name": "персонаж фильмов", "verbose_name_plural": "персонажи фильмов"},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="date",
        ),
        migrations.AddField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="media",
            name="creation_date",
            field=models.DateField(blank=True, default=None, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="personmedia",
            name="person_type",
            field=models.CharField(
                choices=[("actor", "актер"), ("writer", "писатель"), ("director", "режиссер")],
                max_length=20,
                verbose_name="роль",
            ),
        ),
        migrations.CreateModel(
            name="GenreMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("film", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.media")),
                ("genre", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.genre")),
            ],
            options={
                "verbose_name": "жанр фильма",
                "verbose_name_plural": "жанры фильмов",
                "unique_together": {("genre", "film")},
            },
        ),
    ]
