# Generated by Django 3.1 on 2021-04-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_auto_20210430_2034"),
    ]

    operations = []
