# Generated by Django 3.1 on 2021-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_auto_20210501_1747"),
    ]

    operations = []
