# Generated by Django 3.1 on 2021-05-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_auto_20210501_1749"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="genres",
        ),
    ]
