# Generated by Django 3.1 on 2021-05-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_remove_media_genres"),
    ]

    operations = []
