# Generated by Django 3.1 on 2021-05-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_remove_media_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="genres",
            field=models.ManyToManyField(through="movies.GenreMedia", to="movies.Genre"),
        ),
    ]
