# Generated by Django 3.1 on 2021-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'персонаж', 'verbose_name_plural': 'персонаж'},
        ),
        migrations.AlterField(
            model_name='media',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='сертификат'),
        ),
        migrations.AlterField(
            model_name='media',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
