# Generated by Django 3.1 on 2021-05-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210507_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmedia',
            options={'verbose_name': 'участник в создании фильма', 'verbose_name_plural': 'участики в создании фильма'},
        ),
        migrations.AddField(
            model_name='person',
            name='uniq',
            field=models.CharField(default='', max_length=255, verbose_name='ключ уникальности'),
            preserve_default=False,
        ),
    ]
