# Generated by Django 3.1 on 2021-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210511_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uniq',
            field=models.CharField(max_length=255, unique=True, verbose_name='ключ уникальности'),
        ),
    ]
