# Generated by Django 3.1 on 2021-05-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20210511_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('film', 'фильм'), ('serial', 'сериал')], default='film', max_length=20, verbose_name='тип'),
            preserve_default=False,
        ),
    ]
