# Generated by Django 3.1 on 2021-05-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='uniq',
        ),
    ]
