version: '3'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate movies --fake-initial &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py generate_test_data &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_PASS=${SUPERUSER_PASS}
      - DJANGO_SETTINGS_MODULE=config.settings.base
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    expose:
      - '8000'
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    expose:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    build:
      src/.
    depends_on:
      - web
    ports:
      - '81:81'
    restart: always

volumes:
  postgres_data:
